
services:
  janus:
    build:
      context: .
      dockerfile: Dockerfile.janus
    container_name: janus
    ports:
      - "8188:8188" # WebSockets
      - "80:80" #nginx web
      - "5100-5150:5100-5150/udp" # RTP ports for multistream-test
    volumes:
      - ./config:/opt/janus/etc/janus:ro
      - recordings:/opt/janus/recordings
      - logs:/opt/janus/log
    environment:
      - PUBLIC_IP=13.215.249.89
    command: /opt/janus/bin/janus --nat-1-1=${PUBLIC_IP} -d 5
    restart: unless-stopped

  recorder:
    build:
      context: .
      dockerfile: Dockerfile.recorder
    container_name: recorder
    volumes:
      - recordings:/opt/janus/recordings
      - logs:/opt/janus/log:ro
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-ap-southeast-1}
    restart: unless-stopped

volumes:
  recordings:
  logs: