
services:
  janus-gateway:
    image: "canyan/janus-gateway:latest"
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    ports:
      - "8188:8188"
      - "8088:8088"
      - "8089:8089"
      - "8889:8889"
      - "8000:8000"
      - "7088:7088"
      - "7089:7089"
      - "10000-10200:10000-10200/udp"
    volumes:
      - ./janus-config/janus.jcfg:/opt/janus/etc/janus/janus.jcfg
      - ./janus-config/janus.plugin.videoroom.jcfg:/opt/janus/etc/janus/janus.plugin.videoroom.jcfg
      - ./janus-config/janus.transport.pfunix.jcfg:/opt/janus/etc/janus/janus.transport.pfunix.jcfg
      - ./janus-config/janus.transport.websockets.jcfg:/opt/janus/etc/janus/janus.transport.websockets.jcfg
      - ./janus-config/janus.plugin.streaming.jcfg:/opt/janus/etc/janus/janus.plugin.streaming.jcfg
      - ./recordings:/opt/janus/recordings


  web_server:
    user: "root"
    image: httpd:alpine
    ports:
      - 80:80
    volumes:
      - ./html:/usr/local/apache2/htdocs
