apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
  namespace: rtp-system
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS rtp_ports (
        ip VARCHAR(15) NOT NULL,
        port INT NOT NULL,
        allocated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (ip, port)
    );